channel-request.md
After thinking through both LSP-intercept and LSP-request I realized (I think) there's a way to enable both with a single relatively simple API.  The request an end-user makes to the LSP can be exactly the same regardless of which method the channel open is to be fulfilled by.
The only information required to initiate an open channel request with an LSP is who to open the channel with (pubkey@host:port).  The size and duration of the channel are recommended but optional parameters.
With that information the LSP is free to determine the cost/fees it will charge for tying up that amount of liquidity for at least the duration requested.  Once the fee calculation is completed it can return to the client the total cost/fees, an on-chain address, a lightning invoice, and a short channel id …
=> A unified lsp channel request api

Open API/LSPS1.json, Open API/LSPS1.yaml, channel-request.md
As a node-runner who sells channels, I want to give users the option to specify the on-chain fee rate of the channel opening transaction as they may have different time preferences. The value they choose here will affect what price I quote for the channel, so I would like for it to be an option in the request.
=> (proposal) Add optional on_chain_fee_rate to ChannelOrderRequest

LSPS2/README.md, README.md
@npslaney can you also tag Breez?
@cdecker
=> LSPS2: JIT Channels.

LSPS0/README.md
Use underscores in method names in LSPS0, for consistency throughout the spec.
Main edit: Changes `lsps0.listprotocols` to `lsps0.list_protocols`
=> LSPS0: underscores in method names

LSPS2/README.md
Fix the `extra_fee` TLV type number, which is now odd since 3 months ago: https://github.com/lightning/blips/compare/3692c4661d88d7de5634050e17e29597c351666e..ed6f44e9c450b54312ae84413a96a7211093a094#diff-e8862ebd29b16164d75e36bc4ce2552eb76dafff09daeae8959dc89fdf6408bdR24
=> lsps2: fix extra_fee type number

LSPS2/README.md
Small nit: The minimum `payment_size_msat` is smaller than _or equal to_ the fee + `htlc_minimum_msat`. A forward of exactly `htlc_minimum_msat` is eligible for forward as well.
=> lsps2: match payment_size_msat minimum

LSPS0/README.md, LSPS1/README.md, LSPS2/README.md
What is better than unifying versions?  **NOT HAVING TO IMPLEMENT VERSIONS AT ALL**.
The advantages are:
* No more versions.
* Less code: no need to check versions.
* Less roundtrips: no questioning of versions and selecting the version.
* Much less amibiguity in specifications:
* Do we have separate "For implementation", "Stable" etc. states for each VERSION or for each LSPS?
In particular, we SHOULD in fact separate LSPS2 from LSPS4 (***YES*** @SeverinAlexB ***I AM CHANGING MY MIND ABOUT THIS***).  The reason is that LSPS2 has  *fundamentally different flow* from LSPS4:
* LSPS2:
* Get quotes on how much JIT channels cost.
* Buy an SCID.
* Issue invoice
* Receive payment and get JIT channel opened.
* LSPS4:
* Get the permanent SCID
* Issue invoice.
* Receive payment notification. If it …
=> Unified Version Proposal: NO VERSIONING

LSPS0/README.md
Roy Shenfield pointed out that some LSP-servers might not want to advertise themselves in the Telegram-group.
I changed the spec from MUST to MAY and edited the rationale.
=> Allow LSP-servers to not advertise themselves

LSPS1/README.md
- Resolved an issue where `onchain_block_confirmations_required` and `required_onchain_block_confirmations` are used interchangeably.
- Consistently prefer `min_` over `minimum_` in variable names
=> LSPS1: Consistent variable naming

LSPS1/README.md
This change improves consistency.
The method names `lsps1.get_info` and `lsps2.get_info` are consistent.
Within `lsps1` all other methods are using verbs as well
- `lsps1.create_order`
- `lsps1.get_order`
=> Rename lsps1.info to lsps1.get_info

LSPS1/README.md
Allow `minimum_onchain_payment_confirmations` to be `null` if the LSP does not support onchain payments.
=> LSPS1 : allow null for minimum_onchain_payment_confirmations

LSPS1/README.md
The example response for `lsps1.create_order` did not comply to the spec. It should be a `Payment`-object which requires the `minimum_fee_for_0conf` field to be present.
=> Add minimum_fee_for_0conf

LSPS1/README.md
I have removed some fields from the `Channel`-struct. These fields waste bandwidth and add a little bit of complexity to the specification.
I don't think they add any value as clients should maintain the channel-state themselves.
=> Simplify channel struct in LSPS1

LSPS1/README.md
All keys in JSON are following snake case, except for some reason `announceChannel` is camel case. This PR fixes it for consistency.
=> fix announce channel from camel case to snake case

LSPS2/README.md
Previously, the `min_payment_size_msat` and `max_payment_size_msat`
fields were part of the `lsps2.get_info` response, but were not part of
the opening fee parameters the LSP commits to. It was however remarked
that the LSP *may* include them in the `promise` field.
Here, we make the latter non-optional and move the fields into the
`opening_fee_params`. This has three main benefits:
1) The payment size limits are non-negotiable, possibly per-request boundaries the LSP enforces and
hence they should be clearly communicated and committed to via the `promise`.
2) The LSP may want to take different fee rates depending on the
payment size limits, e.g., take a higher fee in exchange for allowing
higher payment sizes.
3) *If* the LSP so far included them in the `promise` calculation, it
was …
=> LSPS2: `{min,max}_payment_size_msat` clarifications

LSPS2/README.md
It turns out that some node implementations simply cannot set `option_zeroconf` in the `open_channel` message, i.e. they have no API that lets this to be set. This prevents such implementations from being used in to implement LSPS2.
The zero-confirmation need is already expressed elsewhere in LSPS2 regarding the timing of `channel_ready` being done immediately after `funding_signed`:
```Markdown
Depending on the `client_trusts_lsp` from the `lsps2.buy` result,
after the client has sent `funding_signed` and the LSP is willing
to broadcast the funding transaction:
* If `client_trusts_lsp` is specified and `true`:
* The LSP MAY wait for the client to send the preimage to the
incoming payment via a `update_fulfill_htlc` before broadcasting
the funding transaction.
* The client MUST NOT wait …
```
=> LSPS2: Remove `option_zeroconf` requirement.

LSPS2/README.md
Fixes #87 
- We drop an erroneous `plus opening_fee` suffix from the channel size calculation
- And refer to the payment size as `htlc_value_msat` in no-MPP+var-invoice mode rather than `payment_size_msat` since the latter is only defined in `MPP+fixed-invoice` mode.
=> LSPS2: Clarify minor `payment_size_msat` things

LSPS1/README.md
The change is quite subtle but the intent becomes clear when you apply
it to a few examples.
The `confirms_within_blocks` is an upper bound on the number of
- blocks between payment and funding-tx-confirmed (See [link](https://github.com/BitcoinAndLightningLayerSpecs/lsp/blob/d07cbb0bcdc1942c4970e4a2ac46f87c63dbdf33/LSPS1/README.md?plain=1#L449C7-L449C154))
- blocks between payment and channel_ready (See [link](https://github.com/BitcoinAndLightningLayerSpecs/lsp/blob/d07cbb0bcdc1942c4970e4a2ac46f87c63dbdf33/LSPS1/README.md?plain=1#L157C36-L157C119))
The `min_channel_confirmations` is the number of confirmations of the funding-tx before sending a `channel_ready`.
```
payment_confirmed            funding tx confirmed            channel_ready
|                             | …
```
=> LSPS1: Semantics of `confirms_within_blocks`

LSPS0/README.md
We falsely implied that an LSP MUST set feature-bit 729.
I've fixed the wording.
This is a replacement for https://github.com/BitcoinAndLightningLayerSpecs/lsp/pull/99
=> LSPS0: LSP-server advertising is optional

LSPS1/README.md
I don't think advertising a website should be in the scope of LSPS1. 
We should probably move icons, websites and pricing info to a separate LSPS.
=> Remove website from LSPS1

LSPS2/README.md
When previously moving the fields into the opening fee params, we forgot to have promise cover them. Here we fix this omission.
=> LSPS2: Have promise cover `{min,max}_payment_size_msat`

LSPS0/README.md, LSPS0/common-schemas.md, LSPS1/README.md, LSPS2/README.md
As discussed in #86, LSPS0 was confusing on error codes that were not specifically mention in LSPS0.
This PR adds clarifying sentences.
CC @tnull
=> LSPS0: Clarify JSON-RPC error codes

LSPS2/README.md
According to LSPS0 common schemas the SCIDs are represented using the common `BBBxTTTxOOO` schema. The example previously given in LSPS2 however seems to follow `000xTTTxBBB`.
Here, we change the example to adhere to the expected schema.
=> LSPS2: Fix `jit_channel_scid` example

LSPS2/README.md
In our conversations about [error messages](https://github.com/BitcoinAndLightningLayerSpecs/lsp/pull/88), we noticed that a `client_rejected` error is missing from LSPS2. It is useful to protect against misbehaving clients similar to the error in LSPS1.
This PR adds the error code to the `lsps2.buy` method.
Requires #88
=> LSPS2: Add client_rejected error

LSPS1/README.md
The payment object should be identical to the one introduced in 3., which indicates the field should be named `bolt11_invoice` rather than `lightning_invoice`.
=> LSPS1: Fix create order response example

LSPS1/README.md
The variable `funding_confirms_withing_blocks` was of type `uint8`. This  means we allowed values from 0<=x<256. This corresponds to a duration of 42 hours.
We are limiting reasonable values and should increase the range of allowed values.
Relates to https://github.com/BitcoinAndLightningLayerSpecs/lsp/issues/112
Relates to https://github.com/alexbosworth/balanceofsatoshis/issues/575
=> lsps1: Use uint16 instead of uint8

LSPS1/README.md, LSPS2/README.md
After multiple people implementing LSPS1 via http, the group acknowledged to add a note to LSPS1/LSPS2 that LSPS0 is an important requirement for implementation.
This PR adds these two notes.
=> LSPS1/LSPS2: Add LSPS0 Required Note

LSPS1/README.md
This PR aims to address a few problems in LSPS1.
I'll provide a few motivating examples of why I believe the changes proposed in this MR are desirable.
Onchain payments are more expensive for the LSP than lightning payments because they create their own utxo. The LSP will have to carry the cost of spending that new utxo at a later point in time.
This PR provides LSP's the option to set a different fee depending on the payment method.
On a related note @2Fast2Bcn [noted](https://github.com/BitcoinAndLightningLayerSpecs/lsp/issues/95#issuecomment-1976025005) that a similar argument could be made for the `expiry_date` of an order. The LSP might want to set a different `expiry_date` depending on the chosen payment option.
See issue: https://github.com/BitcoinAndLightningLayerSpecs/lsp/issues/9 …
=> LSPS1: Explicitly support LSPS1 payment options

LSPS1/README.md
In #101, a few inconsistencies were introduced, but some were also preexisting.
In any case, here we fix a number of minor inconsistencies:
- We align the `invoice` and `address` fields of the BOLT11 payment/onchain payment options when referenced in different parts of the spec.
- We now ensure all monetary amounts / `_sat` fields are JSON strings as defined in LSPS0 Common Schemas.
(cc @ErikDeSmedt)
=> LSPS1: Fix minor inconsistencies

LSPS1/README.md
We fix more inconsistencies that were introduced as part of #101.
=> LSPS1: Fix more inconsistencies

LSPS1/README.md
Mirror back the `refund_onchain_address` given by the client. Solves #122.
=> LSPS1: Fix mirror back refund_onchain_address

LSPS1/README.md
As discussed in the last LSPSpec call, this PR deprecates the `CANCELLED` state for lightning invoices payments. The reason for this is that it is technically redundant to the `REFUNDED` state. 
This change is backwards compatible.
=> LSPS1: Deprecated invoice CANCELLED state
